export PATH="${_SAM2ACT5090_OLD_PATH-}"
if [ -n "${_SAM2ACT5090_OLD_LD_LIBRARY_PATH+x}" ]; then
  export LD_LIBRARY_PATH="${_SAM2ACT5090_OLD_LD_LIBRARY_PATH}"
else
  unset LD_LIBRARY_PATH
fi
if [ -n "${_SAM2ACT5090_OLD_CPATH+x}" ]; then
  export CPATH="${_SAM2ACT5090_OLD_CPATH}"
else
  unset CPATH
fi
unset COPPELIASIM_ROOT
unset QT_QPA_PLATFORM_PLUGIN_PATH
unset CUDA_HOME
unset _SAM2ACT5090_OLD_PATH
unset _SAM2ACT5090_OLD_LD_LIBRARY_PATH
unset _SAM2ACT5090_OLD_CPATH
