#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import pickle
import sys
from pathlib import Path

import numpy as np
import torch

REPO_CODE_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "sam2act"))
if REPO_CODE_ROOT not in sys.path:
    sys.path.insert(0, REPO_CODE_ROOT)

from sam2act.libs.peract.helpers.demo_loading_utils import keypoint_discovery
from sam2act.utils.spatial_graph_memory import SpatialGraphMemoryBank


def natural_episode_key(path: Path) -> int:
    return int(path.name.replace("episode", ""))


def load_demo(episode_dir: Path):
    with (episode_dir / "low_dim_obs.pkl").open("rb") as f:
        return pickle.load(f)


def inspect_episode(
    episode_dir: Path,
    distance_threshold: float,
    ema_alpha: float,
    grip_threshold: float,
    feature_similarity_threshold: float,
):
    demo = load_demo(episode_dir)
    keyframes = keypoint_discovery(demo)
    bank = SpatialGraphMemoryBank(
        distance_threshold=distance_threshold,
        ema_alpha=ema_alpha,
        grip_threshold=grip_threshold,
        feature_similarity_threshold=feature_similarity_threshold,
    )

    summary_bank = []
    transition_counts: dict[tuple[int, int], int] = {}
    prev_idx = None
    assignments = []

    for order, keyframe in enumerate(keyframes):
        obs = demo[keyframe]
        pos = np.asarray(obs.gripper_pose[:3], dtype=np.float32)
        grip_open = np.asarray([float(obs.gripper_open)], dtype=np.float32)

        # Teacher-forced inspection uses GT waypoint/pose and a compact feature
        # derived from the same low-dim state. This avoids rollout drift and
        # reveals whether summary-node construction is sensible by itself.
        feat_vec = np.concatenate(
            [
                np.asarray(obs.gripper_pose, dtype=np.float32),
                grip_open,
            ],
            axis=0,
        )
        feat = torch.from_numpy(feat_vec).float().view(1, 1, -1)
        pos_enc = feat.clone()
        pos_t = torch.from_numpy(pos).float().view(1, 3)
        grip_t = torch.from_numpy(grip_open).float().view(1, 1)

        summary_bank, merged, node_idx = bank.update(
            memory_bank=summary_bank,
            new_feat=feat,
            new_pos_enc=pos_enc,
            new_kf_pos=pos_t,
            new_grip_state=grip_t,
            obs_idx=order,
        )

        if prev_idx is not None:
            key = (int(prev_idx), int(node_idx))
            transition_counts[key] = transition_counts.get(key, 0) + 1
        prev_idx = int(node_idx)

        assignments.append(
            {
                "order": int(order),
                "keyframe": int(keyframe),
                "summary_idx": int(node_idx),
                "merged": bool(merged),
                "gripper_open": float(obs.gripper_open),
                "pose": np.asarray(obs.gripper_pose, dtype=np.float32).tolist(),
            }
        )

    summary_nodes = []
    for node_idx, node in enumerate(summary_bank):
        assigned = [a["order"] for a in assignments if a["summary_idx"] == node_idx]
        summary_nodes.append(
            {
                "summary_idx": int(node_idx),
                "orders": assigned,
                "count": int(node.get("count", 1)),
                "last_obs_idx": int(node["last_obs_idx"]),
                "pos3d": np.asarray(node["pos3d"].detach().cpu(), dtype=np.float32).tolist(),
                "grip": float(node["grip"].detach().cpu().reshape(-1)[0]),
            }
        )

    transitions = [
        {"src": int(src), "dst": int(dst), "count": int(count)}
        for (src, dst), count in sorted(transition_counts.items())
    ]

    return {
        "episode": natural_episode_key(episode_dir),
        "num_frames": len(demo),
        "num_keyframes": len(keyframes),
        "num_summary_nodes": len(summary_bank),
        "assignments": assignments,
        "summary_nodes": summary_nodes,
        "transitions": transitions,
    }


def write_markdown(reports: list[dict], output_md: Path) -> None:
    lines = [
        "# Spatial Graph Teacher-Forced Node Inspection",
        "",
        "This report is generated by `inspect_spatial_graph_teacher_forced_nodes.py`.",
        "It uses GT keyframes and GT gripper state to inspect how summary nodes and transition edges would be built without rollout drift.",
        "",
    ]
    for report in reports:
        lines.extend(
            [
                f"## Episode {report['episode']}",
                "",
                f"- keyframes: `{report['num_keyframes']}`",
                f"- summary nodes: `{report['num_summary_nodes']}`",
                "",
                "| order | keyframe | summary_idx | merged | gripper_open | pos(x,y,z) |",
                "|---:|---:|---:|---:|---:|---|",
            ]
        )
        for a in report["assignments"]:
            x, y, z = a["pose"][:3]
            lines.append(
                f"| {a['order']} | {a['keyframe']} | {a['summary_idx']} | {int(a['merged'])} | {a['gripper_open']:.2f} | ({x:.3f}, {y:.3f}, {z:.3f}) |"
            )
        lines.extend(
            [
                "",
                "| summary_idx | orders | count | grip | pos3d |",
                "|---:|---|---:|---:|---|",
            ]
        )
        for node in report["summary_nodes"]:
            x, y, z = node["pos3d"]
            lines.append(
                f"| {node['summary_idx']} | {node['orders']} | {node['count']} | {node['grip']:.2f} | ({x:.3f}, {y:.3f}, {z:.3f}) |"
            )
        lines.extend(["", "| src | dst | count |", "|---:|---:|---:|"])
        for t in report["transitions"]:
            lines.append(f"| {t['src']} | {t['dst']} | {t['count']} |")
        lines.append("")
    output_md.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", default="put_block_back")
    parser.add_argument("--split", default="test")
    parser.add_argument("--episodes", type=int, default=3)
    parser.add_argument("--data-root", default="/home/cv25/siwon/sam2act/sam2act/data_memory")
    parser.add_argument("--distance-threshold", type=float, default=0.08)
    parser.add_argument("--ema-alpha", type=float, default=0.5)
    parser.add_argument("--grip-threshold", type=float, default=0.35)
    parser.add_argument("--feature-sim-threshold", type=float, default=-1.0)
    parser.add_argument(
        "--output-dir",
        default="/home/cv25/siwon/sam2act_spatial_graph_memory/logs/teacher_forced_nodes",
    )
    args = parser.parse_args()

    episodes_root = Path(args.data_root) / args.split / args.task / "all_variations" / "episodes"
    episode_dirs = sorted(episodes_root.glob("episode*"), key=natural_episode_key)[: args.episodes]
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    reports = []
    for ep_dir in episode_dirs:
        report = inspect_episode(
            episode_dir=ep_dir,
            distance_threshold=args.distance_threshold,
            ema_alpha=args.ema_alpha,
            grip_threshold=args.grip_threshold,
            feature_similarity_threshold=args.feature_sim_threshold,
        )
        reports.append(report)
        ep = report["episode"]
        (output_dir / f"{args.task}_ep{ep}_teacher_forced_nodes.json").write_text(
            json.dumps(report, ensure_ascii=True, indent=2),
            encoding="utf-8",
        )

    write_markdown(reports, output_dir / f"{args.task}_teacher_forced_nodes.md")
    print(json.dumps({"output_dir": str(output_dir), "episodes": len(reports)}, ensure_ascii=True))


if __name__ == "__main__":
    main()
